import datetime
from app.models.enums import RuleOperator, RuleAppliesTo, ApplicationMode

AGRICULTURE_SCHEMES = [
    {
        "scheme_code": "TN-AGRI-PM-KISAN",
        "name_english": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) Direct Income Support",
        "name_tamil": "பிரதமர் கிசான் சம்மான் நிதி (PM-KISAN) விவசாயிகளுக்கான நேரடி வருவாய் உதவி",
        "name_transliteration": "PM Kisan Samman Nidhi Vivasayigal Uvithogai",
        "department": "Agriculture and Farmers Welfare",
        "category": "farmer_income_support",
        "description_english": "Direct income support of ₹6,000 per year in three equal installments of ₹2,000 every four months to all landholding farmer families across Tamil Nadu.",
        "description_tamil": "விவசாய நிலம் வைத்துள்ள விவசாய குடும்பங்களுக்கு ஆண்டுக்கு ₹6,000 (4 மாதங்களுக்கு ஒருமுறை ₹2,000 வீதம்) நேரடியாக வங்கிக் கணக்கில் வழங்கும் திட்டம்.",
        "benefit_amount": "₹6,000/year (₹2,000 every 4 months)",
        "source_url": "https://pmkisan.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "ஆதார் அட்டை (Aadhaar Card with e-KYC)",
            "நிலப் பட்டா / சிட்டா (Patta / Chitta document)",
            "நில ஆவணம் மற்றும் அடங்கல் (Land Adangal)",
            "ஆதார் இணைக்கப்பட்ட வங்கி கணக்கு புத்தகம் (NPCI Aadhar Seeded Bank Account)",
        ],
        "application_office": "வட்டார வேளாண்மை உதவி இயக்குநர் அலுவலகம் / இ-சேவை மையம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://pmkisan.gov.in/",
        "processing_time_estimate": "15 முதல் 30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "5.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-KURUVAI-PACKAGE",
        "name_english": "Kuruvai Cultivation Special Package Scheme for Delta Paddy Farmers",
        "name_tamil": "டெல்டா குறுவை சாகுபடி சிறப்பு தொகுப்புத் திட்டம் (இலவச உரம் & விதைகள்)",
        "name_transliteration": "Delta Kuruvai Sagubadi Sirappu Thoguppu",
        "department": "Agriculture and Farmers Welfare",
        "category": "input_subsidy",
        "description_english": "Special agricultural input package providing 100% subsidy on certified paddy seeds, urea, DAP, and potash to delta district farmers taking up Kuruvai season paddy cultivation.",
        "description_tamil": "காவிரி டெல்டா மற்றும் பாசனப் பகுதிகளில் குறுவை நெல் சாகுபடி செய்யும் விவசாயிகளுக்கு 100% மானியத்தில் சான்று பெற்ற விதைகள், யூரியா, டிஏபி, பொட்டாஷ் வழங்கும் திட்டம்.",
        "benefit_amount": "100% Subsidy on Seeds and Fertilizers (₹4,000/acre value)",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "உழவர் பதிவு எண் (Uzhavar Registration ID / AGRISNET)",
            "சிட்டா / பட்டா நகல் (Patta / Chitta)",
            "கிராம நிர்வாக அலுவலர் (VAO) வழங்கும் குறுவை சாகுபடி சான்றிதழ் / அடங்கல்",
            "ஆதார் அட்டை மற்றும் குடும்ப அட்டை நகல்",
        ],
        "application_office": "வேளாண் விரிவாக்க மையம் (Agricultural Extension Centre) / உழவர் அலுவலர்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnagrisnet.tn.gov.in/",
        "processing_time_estimate": "7 முதல் 15 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "crop_type",
                "operator": RuleOperator.EQUALS,
                "value": "paddy",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "5.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-MICRO-IRRIGATION-MIF",
        "name_english": "Micro Irrigation Scheme (Drip and Sprinkler Subsidy under PMKSY)",
        "name_tamil": "நுண்ணீர்ப் பாசனத் திட்டம் (சிறு/குறு விவசாயிகளுக்கு 100% மானியத்தில் சொட்டு நீர்ப்பாசனம்)",
        "name_transliteration": "Nunneer Paasana Thittam Sottuneer Paasanam",
        "department": "Agriculture and Farmers Welfare",
        "category": "irrigation_subsidy",
        "description_english": "100% subsidy for small and marginal farmers (up to 5 acres) and 75% subsidy for other farmers to install drip and sprinkler irrigation systems to conserve ground water.",
        "description_tamil": "பாசன நீரை சேமிக்க சிறு மற்றும் குறு விவசாயிகளுக்கு 100% மானியத்திலும், இதர விவசாயிகளுக்கு 75% மானியத்திலும் சொட்டுநீர் மற்றும் தெளிப்பு நீர்ப்பாசன கருவிகள் அமைத்தல்.",
        "benefit_amount": "100% Subsidy for Small/Marginal Farmers, 75% for other farmers",
        "source_url": "https://tnhorticulture.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சிறு/குறு விவசாயி சான்றிதழ் (வட்டாட்சியர்/VAO சான்றிதழ்)",
            "நில உரிமை பட்டா, சிட்டா மற்றும் நில வரைபடம் (FMB sketch)",
            "கிணறு / ஆழ்துளை கிணறு பாசன நீர் ஆதாரம் இருப்பதற்கான சான்று",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "வட்டார தோட்டக்கலை / வேளாண்மை உதவி இயக்குநர் அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnhorticulture.tn.gov.in/",
        "processing_time_estimate": "30 முதல் 45 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "5.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-UZHAVAR-PATHUKAPPU-PENSION",
        "name_english": "Chief Minister's Farmers Social Security Scheme (Uzhavar Pathukappu Thittam) Monthly Pension",
        "name_tamil": "முதலமைச்சரின் உழவர் பாதுகாப்புத் திட்டம் - முதியோர் ஓய்வூதியம்",
        "name_transliteration": "Uzhavar Pathukappu Thittam Mudhiyor Oivoodhiyam",
        "department": "Agriculture and Farmers Welfare",
        "category": "pension",
        "description_english": "Monthly pension of ₹1,000 provided to aged small, marginal, and tenant farmers and agricultural labourers aged 60 and above registered under Uzhavar Pathukappu Thittam.",
        "description_tamil": "உழவர் பாதுகாப்புத் திட்டத்தில் பதிவுசெய்த 60 வயது பூர்த்தியடைந்த சிறு, குறு, குத்தகை விவசாயிகள் மற்றும் விவசாயத் தொழிலாளர்களுக்கு மாதம் ₹1,000 ஓய்வூதியம்.",
        "benefit_amount": "₹1,000/month",
        "source_url": "https://www.tnesevai.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "முதலமைச்சரின் உழவர் பாதுகாப்பு அட்டை (Uzhavar Card)",
            "வயதுச் சான்றிதழ் (Age Proof - 60 வயது பூர்த்தி)",
            "வருமானச் சான்றிதழ் (Income Certificate)",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "வட்டாட்சியர் அலுவலகம் (சமூகப் பாதுகாப்புத் திட்டம்) / இ-சேவை மையம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://www.tnesevai.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "60",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "2.5",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "10000",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-CROP-INSURANCE-PMFBY",
        "name_english": "Pradhan Mantri Fasal Bima Yojana (PMFBY) Crop Insurance Scheme",
        "name_tamil": "பிரதம மந்திரி பயிர் காப்பீட்டுத் திட்டம் (PMFBY)",
        "name_transliteration": "PM Fasal Bima Yojana Payir Kaapeedu",
        "department": "Agriculture and Farmers Welfare",
        "category": "crop_insurance",
        "description_english": "Comprehensive crop insurance protection covering yield loss due to non-preventable risks (natural drought, floods, inundation, pests, and unseasonal rainfall) at nominal farmer premium rates (1.5% to 2%).",
        "description_tamil": "வறட்சி, வெள்ளம், பூச்சித் தாக்குதல் போன்ற இயற்கை இடர்பாடுகளால் ஏற்படும் பயிர் இழப்புகளுக்கு குறைந்த பிரீமியம் விகிதத்தில் முழு நிதி இழப்பீடு வழங்கும் பயிர் காப்பீட்டுத் திட்டம்.",
        "benefit_amount": "Full Sum Insured on Crop Loss due to drought/flood",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பயிர் சாகுபடி அடங்கல் (Adangal from VAO / e-Adangal)",
            "பட்டா / சிட்டா நகல் (Patta / Chitta document)",
            "வங்கி கணக்கு புத்தகம் (Bank Passbook)",
            "ஆதார் அட்டை (Aadhaar Card)",
        ],
        "application_office": "தொடக்க வேளாண்மை கூட்டுறவு கடன் சங்கம் (PACCS) / பொது இ-சேவை மையம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://pmfby.gov.in/",
        "processing_time_estimate": "பயிர் அறுவடை பரிசோதனை முடிவுகளுக்குப் பின்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-MILLETS-MISSION",
        "name_english": "Tamil Nadu Millet Mission Cultivation Incentive and Seed Subsidy",
        "name_tamil": "தமிழ்நாடு சிறுதானிய இயக்கம் - சாகுபடி மானியம் மற்றும் விதைகள்",
        "name_transliteration": "Tamil Nadu Sirudhaaniya Iyakkam",
        "department": "Agriculture and Farmers Welfare",
        "category": "crop_incentive",
        "description_english": "Financial incentive of ₹5,000 per hectare along with free bio-fertilizers and quality seeds for farmers cultivating millets like ragi, kambu, thinai, and varagu.",
        "description_tamil": "கேழ்வரகு, கம்பு, தினை, வரகு உள்ளிட்ட சிறுதானியங்களை சாகுபடி செய்யும் விவசாயிகளுக்கு ஹெக்டேருக்கு ₹5,000 மானியம் மற்றும் சான்று பெற்ற விதைகள் வழங்கும் திட்டம்.",
        "benefit_amount": "₹5,000/hectare Input Subsidy",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சிறுதானிய சாகுபடி அடங்கல் (Adangal proof for Millets)",
            "பட்டா / சிட்டா நகல்",
            "உழவர் பதிவு அட்டை",
            "வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "வட்டார வேளாண் விரிவாக்க மையம் (AEC)",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnagrisnet.tn.gov.in/",
        "processing_time_estimate": "15 முதல் 30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "crop_type",
                "operator": RuleOperator.EQUALS,
                "value": "millets",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-SOLAR-PUMP-SUBSIDY",
        "name_english": "Standalone Solar Powered Pumping System Subsidy Scheme (PM-KUSUM Component-B)",
        "name_tamil": "விவசாயிகளுக்கு 70% மானியத்தில் தனித்து இயங்கும் சூரியசக்தி பம்புசெட்டுகள் அமைத்தல்",
        "name_transliteration": "Sooriya Sakthi Pumbset Maaniyam",
        "department": "Agriculture and Farmers Welfare",
        "category": "solar_irrigation",
        "description_english": "Provision of standalone AC/DC solar agricultural pumping systems (up to 10 HP) with 70% capital subsidy from Central and State Governments.",
        "description_tamil": "மின் இணைப்பு இல்லாத விவசாய நிலங்களுக்கு 70% மானியத்தில் 5 முதல் 10 குதிரைத்திறன் கொண்ட சூரியசக்தி பம்புசெட்டுகள் அமைக்கும் திட்டம்.",
        "benefit_amount": "70% Subsidy on Solar Pump System (up to ₹2,00,000)",
        "source_url": "https://aed.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பட்டா / சிட்டா மற்றும் நில உரிமை ஆவணம்",
            "கிணறு / ஆழ்துளை கிணறு நிலத்தடி நீர் கிடைக்கும் சான்றிதழ்",
            "விவசாயி பங்குத் தொகை செலுத்துவதற்கான உறுதிமொழி",
            "ஆதார் அட்டை மற்றும் குடும்ப அட்டை",
        ],
        "application_office": "வேளாண் பொறியியல் துறை உதவி செயற்பொறியாளர் அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://aed.tn.gov.in/",
        "processing_time_estimate": "45 முதல் 60 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "1.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-FARM-MACHINERY-SUBSIDY",
        "name_english": "Subsidized Agricultural Machinery & Power Tillers Scheme (SMAM)",
        "name_tamil": "வேளாண் இயந்திரமயமாக்கல் திட்டம் - பவர்டில்லர் மற்றும் கருவிகள் மானியம்",
        "name_transliteration": "Velan Iyandhiramayamakkal Thittam",
        "department": "Agriculture and Farmers Welfare",
        "category": "machinery_subsidy",
        "description_english": "Capital subsidy of up to 50% for SC, ST, women, and small/marginal farmers for purchasing power tillers, rotavators, weeders, and paddy transplanters.",
        "description_tamil": "பவர்டில்லர், களை எடுக்கும் கருவி, நெல் நடவு இயந்திரம் உள்ளிட்ட வேளாண் கருவிகள் வாங்க சிறு, குறு, பெண் விவசாயிகளுக்கு 50% வரை மானியம்.",
        "benefit_amount": "50% Subsidy for SC/ST/Women/Small Farmers (up to ₹1,00,000)",
        "source_url": "https://aed.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சிறு/குறு விவசாயி சான்றிதழ் (Small Farmer Certificate)",
            "பட்டா மற்றும் சிட்டா நகல்",
            "விவசாய இயந்திர விலைப்பட்டியல் (Quotation from approved dealer)",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "வேளாண் பொறியியல் துறை அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://aed.tn.gov.in/",
        "processing_time_estimate": "30 முதல் 45 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.5",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-KALAIGNAR-ALL-VILLAGE",
        "name_english": "Kalaignar All Village Integrated Agriculture Development Programme (KAVIADP)",
        "name_tamil": "கலைஞரின் அனைத்து கிராம ஒருங்கிணைந்த வேளாண் வளர்ச்சித் திட்டம்",
        "name_transliteration": "Kalaignarin Anaithu Grama Oringinaindha Velan Thittam",
        "department": "Agriculture and Farmers Welfare",
        "category": "integrated_development",
        "description_english": "Holistic village-level mission providing free coconut saplings, vegetable seed kits, hand sprayers, and horticulture saplings to bring fallow lands under cultivation.",
        "description_tamil": "கிராமப் பஞ்சாயத்துகளில் தரிசு நிலங்களை சாகுபடிக்கு கொண்டு வர இலவச தென்னங்கன்றுகள், காய்கறி விதை பெட்டகங்கள், கைத்தெளிப்பான்கள் வழங்கும் திட்டம்.",
        "benefit_amount": "Free Coconut Seedlings, Fruit Plants and Hand Sprayers",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "குடும்ப அட்டை நகல்",
            "ஆதார் அட்டை நகல்",
            "கிராம பஞ்சாயத்து இருப்பிடச் சான்று",
        ],
        "application_office": "கிராம ஊராட்சி மன்ற அலுவலகம் / வேளாண் விரிவாக்க மையம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "கிராம முகாம்களில் உடனடியாக வழங்கப்படும்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "5.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-PULSES-PRODUCTION-MISSION",
        "name_english": "National Food Security Mission - Pulses Production and Quality Seed Distribution",
        "name_tamil": "தேசிய உணவுப் பாதுகாப்பு இயக்கம் - பருப்பு வகை பயிர்கள் ஊக்கத்தொகை",
        "name_transliteration": "Paruppu Vagaigal Saagubadi Maaniyam",
        "department": "Agriculture and Farmers Welfare",
        "category": "crop_incentive",
        "description_english": "Incentive support and 50% subsidy on certified blackgram and greengram seeds to promote pulses cultivation as bund crops and rice-fallows.",
        "description_tamil": "உளுந்து, பாசிப்பயறு உள்ளிட்ட பருப்பு வகை பயிர்களை வரப்புப் பயிராகவும் நெல் தரிசிலும் சாகுபடி செய்ய 50% விதை மானியம் மற்றும் ஊக்கத்தொகை.",
        "benefit_amount": "₹3,000/hectare Input Incentive",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "நிலப் பட்டா / சிட்டா நகல்",
            "பயிர் அடங்கல் (Adangal proof for Pulses)",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "வட்டார வேளாண்மை விரிவாக்க மையம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnagrisnet.tn.gov.in/",
        "processing_time_estimate": "15 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "crop_type",
                "operator": RuleOperator.EQUALS,
                "value": "pulses",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-ORGANIC-FARMING-SUBSIDY",
        "name_english": "Paramparagat Krishi Vikas Yojana (PKVY) Organic Farming Promotion",
        "name_tamil": "பாரம்பரிய இயற்கை விவசாய மேம்பாட்டுத் திட்டம் - இடுபொருட்கள் மானியம்",
        "name_transliteration": "Iyarkai Vivasaayam PKVY Maaniyam",
        "department": "Agriculture and Farmers Welfare",
        "category": "organic_farming",
        "description_english": "Financial assistance of ₹15,000 per hectare over 3 years for organic inputs, vermicompost units, bio-fertilizers, and organic certification.",
        "description_tamil": "இயற்கை மற்றும் இயற்கை உரம் சார்ந்த சாகுபடியை ஊக்குவிக்க 3 ஆண்டுகளில் ஹெக்டேருக்கு ₹15,000 இடுபொருள் மானியம் மற்றும் சான்றளிப்பு உதவி.",
        "benefit_amount": "₹15,000/hectare over 3 years",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பட்டா, சிட்டா நகல்",
            "இயற்கை விவசாயக் குழுவில் (Organic Cluster) உறுப்பினர் சான்று",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "வட்டார வேளாண் விரிவாக்க மையம் (AEC)",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.5",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-OILSEEDS-EXPANSION",
        "name_english": "Oilseeds Production Expansion and Groundnut Seed Subsidy Scheme",
        "name_tamil": "எண்ணெய் வித்துக்கள் சாகுபடி பரப்பு விரிவாக்கம் மற்றும் விதை மானியம்",
        "name_transliteration": "Ennai Vithukkal Nilakkadalai Maaniyam",
        "department": "Agriculture and Farmers Welfare",
        "category": "crop_incentive",
        "description_english": "Distribution of certified groundnut, sesame, and sunflower seeds at 50% subsidy to expand edible oilseed production in dry and rainfed tracts.",
        "description_tamil": "நிலக்கடலை, எள், சூரியகாந்தி உள்ளிட்ட எண்ணெய் வித்துக்கள் பயிரிடும் விவசாயிகளுக்கு 50% மானியத்தில் சான்று பெற்ற விதைகள் வழங்கும் திட்டம்.",
        "benefit_amount": "50% Subsidy on Certified Oilseeds",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பட்டா மற்றும் சிட்டா நகல்",
            "விவசாயி அடையாள அட்டை",
            "ஆதார் அட்டை",
        ],
        "application_office": "வட்டார வேளாண் விரிவாக்க மையம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnagrisnet.tn.gov.in/",
        "processing_time_estimate": "7 முதல் 15 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "crop_type",
                "operator": RuleOperator.EQUALS,
                "value": "oilseeds",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-DRYLAND-DEVELOPMENT-MISSION",
        "name_english": "Mission on Sustainable Dryland Agriculture (MSDA) for Rainfed Farmers",
        "name_tamil": "நீடித்த நிலையான மானாவாரி வேளாண்மை இயக்கம் (MSDA)",
        "name_transliteration": "Maanavaari Velanmai Iyakkam MSDA",
        "department": "Agriculture and Farmers Welfare",
        "category": "dryland_mission",
        "description_english": "Cluster-based soil health improvement, deep summer ploughing subsidy, and drought-tolerant seed distribution for rainfed and dryland farmers.",
        "description_tamil": "மழை நம்பி விவசாயம் செய்யும் மானாவாரி நிலங்களில் கோடை உழவு மானியம், மண்வள மேலாண்மை மற்றும் வறட்சியைத் தாங்கும் பயிர் விதைகள் வழங்கும் திட்டம்.",
        "benefit_amount": "Free Soil Health Management and Agronomic Inputs",
        "source_url": "https://tnagrisnet.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "மானாவாரி நிலப் பட்டா மற்றும் அடங்கல்",
            "ஆதார் அட்டை",
            "வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "வட்டார வேளாண் விரிவாக்க மையம் (AEC)",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "15 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "5.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-HORTICULTURE-PLANTING-MATERIAL",
        "name_english": "National Horticulture Mission - Subsidized Fruit Plants and Shade Net Polyhouses",
        "name_tamil": "தோட்டக்கலை பயிர்கள் நடவு மற்றும் பசுமை குடில் அமைக்கும் மானியத் திட்டம்",
        "name_transliteration": "Thottakallai Payirgal Pasumai Kudil Maaniyam",
        "department": "Agriculture and Farmers Welfare",
        "category": "horticulture_subsidy",
        "description_english": "40% to 50% subsidy on high yielding fruit saplings (Mango, Guava, Acid Lime) and protected cultivation shade nets to boost horticulture income.",
        "description_tamil": "மா, கொய்யா, எலுமிச்சை உள்ளிட்ட பழ மரக்கன்றுகள் நடவு செய்வதற்கும் பசுமை நிழல்வலை குடில் அமைப்பதற்கும் 40% முதல் 50% வரை மானியம்.",
        "benefit_amount": "40% to 50% Capital Subsidy on Planting Material",
        "source_url": "https://tnhorticulture.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "தோட்டக்கலை நில பட்டா, சிட்டா மற்றும் வரைபடம்",
            "சிறு/குறு விவசாயி சான்றிதழ்",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "வட்டார தோட்டக்கலை உதவி இயக்குநர் அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnhorticulture.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "crop_type",
                "operator": RuleOperator.EQUALS,
                "value": "horticulture",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.5",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-FARM-POND-SUBSIDY",
        "name_english": "Rainwater Harvesting Farm Ponds Construction Subsidy for Dryland Farmers",
        "name_tamil": "மானாவாரி விவசாய நிலங்களில் பண்ணைக் குட்டைகள் அமைக்க 100% மானியத் திட்டம்",
        "name_transliteration": "Pannai Kuttaigal Amaikka 100% Maaniyam",
        "department": "Agriculture and Farmers Welfare",
        "category": "water_conservation",
        "description_english": "100% grant (up to ₹1,00,000) for excavation of rainwater harvesting farm ponds (dimensions 30m x 30m x 1.5m) in drylands to store runoff water.",
        "description_tamil": "மழைநீரை நிலத்தில் சேமித்து பாசனத்திற்கு பயன்படுத்த விவசாய நிலத்தில் பண்ணைக்குட்டை அமைக்க 100% முழு மானியம் (ரூ.1,00,000 வரை).",
        "benefit_amount": "100% Subsidy (up to ₹1,00,000 for pond excavation)",
        "source_url": "https://aed.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "நிலப் பட்டா, சிட்டா மற்றும் அடங்கல்",
            "பண்ணைக்குட்டை அமைக்க உத்தேசித்துள்ள இடத்தின் வரைபடம்",
            "ஆதார் அட்டை மற்றும் குடும்ப அட்டை",
        ],
        "application_office": "வேளாண் பொறியியல் துறை உதவி செயற்பொறியாளர் அலுவலகம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "1.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-AGRI-COCONUT-DEVELOPMENT",
        "name_english": "Integrated Coconut Development Scheme (Seedling Distribution & Pest Management)",
        "name_tamil": "ஒருங்கிணைந்த தென்னை வளர்ச்சித் திட்டம் - கன்றுகள் மற்றும் பூச்சி மேலாண்மை",
        "name_transliteration": "Oringinaindha Thennai Valarchi Thittam",
        "department": "Agriculture and Farmers Welfare",
        "category": "crop_incentive",
        "description_english": "50% subsidy on hybrid coconut seedlings, organic manure, and biological control agents for coconut rhinoceros beetle and red palm weevil management.",
        "description_tamil": "வீரிய ஒட்டு தென்னங்கன்றுகள் வாங்குவதற்கும், காண்டாமிருக வண்டு தாக்குதலைக் கட்டுப்படுத்தவும் தென்னை விவசாயிகளுக்கு 50% மானியம்.",
        "benefit_amount": "50% Subsidy on Hybrid Seedlings",
        "source_url": "https://tnhorticulture.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "தென்னை சாகுபடி பட்டா மற்றும் சிட்டா",
            "விவசாயி அடையாள அட்டை",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "வட்டார தோட்டக்கலை அலுவலர் அலுவலகம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnhorticulture.tn.gov.in/",
        "processing_time_estimate": "15 முதல் 20 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "farmer",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "crop_type",
                "operator": RuleOperator.EQUALS,
                "value": "coconut",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "land_holding_acres",
                "operator": RuleOperator.GREATER_THAN,
                "value": "0.0",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
]
