import datetime
from app.models.enums import RuleOperator, RuleAppliesTo, ApplicationMode

EDUCATION_SCHEMES = [
    {
        "scheme_code": "TN-EDU-POST-MATRIC-SC",
        "name_english": "Post-Matric Scholarship Scheme for SC and ST Students",
        "name_tamil": "பட்டியலினம் மற்றும் பழங்குடியினர் மாணவர்களுக்கான போஸ்ட் மெட்ரிக் கல்வி உதவித்தொகை",
        "name_transliteration": "Post-Matric Kalvi Uvithogai SC ST",
        "department": "Education",
        "category": "scholarship",
        "description_english": "100% compulsory tuition fee waiver, maintenance allowance, and book grant for SC and ST students pursuing Higher Secondary and College degree courses.",
        "description_tamil": "11, 12-ஆம் வகுப்பு மற்றும் கல்லூரி உயர்கல்வி பயிலும் பட்டியலினம் (SC) மற்றும் பழங்குடியினர் (ST) மாணவர்களுக்கான முழு கல்விக் கட்டண விலக்கு மற்றும் உதவித்தொகை.",
        "benefit_amount": "₹10,000 to ₹50,000/year (100% Fee Waiver)",
        "source_url": "https://adwscholarship.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (Community Certificate)",
            "வருமானச் சான்றிதழ் (Income Certificate)",
            "மதிப்பெண் சான்றிதழ் (Marksheet)",
            "வங்கி கணக்கு புத்தகம் (Bank Passbook)",
            "கல்லூரி சேர்க்கை சான்று (College Bonafide Certificate)",
        ],
        "application_office": "கல்லூரி முதல்வர் அலுவலகம் / மாவட்ட ஆதிதிராவிடர் நல அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://adwscholarship.tn.gov.in/",
        "processing_time_estimate": "30 முதல் 45 நாட்கள்",
        "rules": [
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "SC,ST",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "higher_secondary,graduate,postgraduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "20833",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-PRE-MATRIC-SC",
        "name_english": "Pre-Matric Scholarship Scheme for SC and ST Students (Classes 9 & 10)",
        "name_tamil": "பட்டியலினம் மற்றும் பழங்குடியின 9, 10-ஆம் வகுப்பு மாணவர்களுக்கான ப்ரீ-மெட்ரிக் கல்வி உதவித்தொகை",
        "name_transliteration": "Pre-Matric Kalvi Uvithogai SC ST",
        "department": "Education",
        "category": "scholarship",
        "description_english": "Annual educational assistance and book grant provided to SC and ST day-scholars and hostellers studying in classes 9 and 10.",
        "description_tamil": "9 மற்றும் 10-ஆம் வகுப்பு பயிலும் பட்டியலினம் மற்றும் பழங்குடியின பள்ளி மாணவர்களுக்கான வருடாந்திர கல்வி உதவித்தொகை.",
        "benefit_amount": "₹3,500/year",
        "source_url": "https://adwscholarship.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (Community Certificate)",
            "வருமானச் சான்றிதழ் (Income Certificate)",
            "பள்ளி சேர்க்கை சான்று (School Bonafide)",
            "வங்கி கணக்கு புத்தகம் (Bank Passbook)",
        ],
        "application_office": "பள்ளி தலைமை ஆசிரியர் அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://adwscholarship.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "SC,ST",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "17",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-POST-MATRIC-BC-MBC",
        "name_english": "Post-Matric Scholarship for BC, MBC, and DNC Students",
        "name_tamil": "பிற்படுத்தப்பட்டோர் மற்றும் மிகவும் பிற்படுத்தப்பட்டோர் மாணவர்களுக்கான போஸ்ட் மெட்ரிக் கல்வி உதவித்தொகை",
        "name_transliteration": "Post-Matric Kalvi Uvithogai BC MBC",
        "department": "Education",
        "category": "scholarship",
        "description_english": "Tuition fees, special fees, and maintenance grant for BC, MBC, and DNC students in polytechnic, arts, science, and professional colleges.",
        "description_tamil": "கல்லூரி மற்றும் பாலிடெக்னிக் பயிலும் பிற்படுத்தப்பட்டோர், மிகவும் பிற்படுத்தப்பட்டோர் மற்றும் சீர்மரபினர் மாணவர்களுக்கான உதவித்தொகை.",
        "benefit_amount": "₹4,000 to ₹15,000/year",
        "source_url": "https://bcbmcmw.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (Community Certificate)",
            "வருமானச் சான்றிதழ் (Income Certificate)",
            "கல்லூரி அடையாள அட்டை மற்றும் கட்டண ரசீது",
            "வங்கி கணக்கு விவரம் (Aadhaar Seeded Bank Account)",
        ],
        "application_office": "கல்லூரி முதல்வர் / மாவட்ட பிற்படுத்தப்பட்டோர் நல அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://bcbmcmw.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "BC,MBC,DNC",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "higher_secondary,graduate,postgraduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "16666",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-FREE-EDUCATION-BC-DEGREE",
        "name_english": "Free Education Scheme for BC, MBC, and DNC 3-Year Undergraduate Degree Students",
        "name_tamil": "பிற்படுத்தப்பட்டோர் மற்றும் மிகவும் பிற்படுத்தப்பட்டோர் பட்டப்படிப்பு மாணவர்களுக்கான இலவசக் கல்வித் திட்டம்",
        "name_transliteration": "Ilavasa Kalvi Thittam BC MBC Degree",
        "department": "Education",
        "category": "scholarship",
        "description_english": "Complete exemption from tuition fees and special fees for BC, MBC, and DNC students pursuing 3-year undergraduate arts and science degrees in government and aided colleges.",
        "description_tamil": "அரசு மற்றும் அரசு உதவிபெறும் கலை, அறிவியல் கல்லூரிகளில் 3 ஆண்டு இளங்கலை பயிலும் BC/MBC/DNC மாணவர்களுக்கு முழு கல்விக் கட்டண விலக்கு.",
        "benefit_amount": "முழு கல்விக் கட்டண விலக்கு (Full Tuition Fee Exemption)",
        "source_url": "https://bcbmcmw.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (Community Certificate)",
            "வருமானச் சான்றிதழ் (வருமானம் ₹1,00,000-க்குள்)",
            "12-ஆம் வகுப்பு மதிப்பெண் சான்றிதழ்",
            "குடும்ப அட்டை நகல்",
        ],
        "application_office": "கல்லூரி அலுவலகம் / இ-சேவை மையம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://bcbmcmw.tn.gov.in/",
        "processing_time_estimate": "20 நாட்கள்",
        "rules": [
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "BC,MBC,DNC",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "graduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "10000",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-TAMIL-PUDHALVAN",
        "name_english": "Tamil Pudhalvan Higher Education Assurance Scheme for Boys",
        "name_tamil": "தமிழ்ப்புதல்வன் திட்டம் (அரசுப் பள்ளி மாணவர்கள் உயர்கல்வி உதவி)",
        "name_transliteration": "Tamil Pudhalvan Thittam",
        "department": "Education",
        "category": "monthly_allowance",
        "description_english": "Monthly financial assistance of ₹1,000 directly credited to bank accounts of male students from government schools pursuing undergraduate degrees, diplomas, and ITI courses.",
        "description_tamil": "அரசுப் பள்ளிகளில் (6 முதல் 12 வரை) படித்து உயர்கல்வி சேரும் மாணவர்களுக்கு மாதம் ₹1,000 உதவித்தொகை வழங்கும் திட்டம்.",
        "benefit_amount": "₹1,000/month",
        "source_url": "https://tamilpudhalvan.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "ஆதார் அட்டை (Aadhaar Card)",
            "அரசுப் பள்ளி பயின்ற சான்றிதழ் (EMIS School Study Certificate)",
            "கல்லூரி சேர்க்கை அடையாள அட்டை",
            "மாணவர் பெயரிலான ஆதார் இணைக்கப்பட்ட வங்கிக் கணக்கு புத்தகம்",
        ],
        "application_office": "கல்லூரி இணையதள ஒருங்கிணைப்பாளர் / போர்ட்டல்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tamilpudhalvan.tn.gov.in/",
        "processing_time_estimate": "15 முதல் 30 நாட்கள்",
        "rules": [
            {
                "field_name": "gender",
                "operator": RuleOperator.EQUALS,
                "value": "male",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "graduate,postgraduate,higher_secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "17",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-FIRST-GRADUATE-FEE-CONCESSION",
        "name_english": "First Generation Graduate Tuition Fee Concession Scheme",
        "name_tamil": "முதல் தலைமுறை பட்டதாரி கல்விக் கட்டணச் சலுகைத் திட்டம்",
        "name_transliteration": "Mudhal Thalaimurai Pattadhari Katana Salugai",
        "department": "Education",
        "category": "tuition_concession",
        "description_english": "Full tuition fee waiver for students who are the first graduates in their family admitted through single-window counseling in professional degree courses (Engineering, Medical, Agri).",
        "description_tamil": "குடும்பத்தில் முதல் பட்டதாரியாக பொறியியல், மருத்துவம், வேளாண்மை உள்ளிட்ட தொழில்முறை பட்டப்படிப்பில் சேரும் மாணவர்களுக்கு முழுக் கல்விக் கட்டணச் சலுகை.",
        "benefit_amount": "₹20,000 to ₹40,000/year Tuition Waiver",
        "source_url": "https://tnesevai.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வட்டாட்சியர் வழங்கும் முதல் பட்டதாரி சான்றிதழ் (First Graduate Certificate)",
            "குடும்ப உறுப்பினர்களின் கல்விச் சான்றிதழ்கள் அல்லது உறுதிமொழிப் படிவம்",
            "ஒற்றைச் சாளர சேர்க்கை ஆணை (Allotment Order)",
            "குடும்ப அட்டை மற்றும் ஆதார் அட்டை",
        ],
        "application_office": "வட்டாட்சியர் அலுவலகம் / இ-சேவை மையம் மற்றும் சேர்க்கை கல்லூரி",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnesevai.tn.gov.in/",
        "processing_time_estimate": "15 நாட்கள்",
        "rules": [
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "graduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "first_graduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-FREE-LAPTOP",
        "name_english": "Chief Minister's Free Laptop Scheme for 12th Standard Students",
        "name_tamil": "முதலமைச்சரின் விலையில்லா மடிக்கணினி திட்டம்",
        "name_transliteration": "Vilayilla Madikanini Thittam",
        "department": "Education",
        "category": "education_device",
        "description_english": "Distribution of free laptops to students studying in government and government-aided schools to bridge the digital divide and encourage digital literacy.",
        "description_tamil": "அரசு மற்றும் அரசு உதவிபெறும் பள்ளிகளில் பயிலும் மேல்நிலைக் கல்வி (12-ஆம் வகுப்பு) மாணவர்களுக்கு வழங்கப்படும் இலவச மடிக்கணினி.",
        "benefit_amount": "இலவச மடிக்கணினி (Free Laptop Computer)",
        "source_url": "https://tnschools.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பள்ளி அடையாள அட்டை (School ID Card)",
            "ஆதார் அட்டை (Aadhaar Card)",
            "மாணவர் EMIS எண்",
        ],
        "application_office": "பள்ளி தலைமை ஆசிரியர் அலுவலகம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "கல்வியாண்டு விநியோக அட்டவணைப்படி",
        "rules": [
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "higher_secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "16",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "19",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-FREE-BICYCLE",
        "name_english": "Free Bicycle Scheme for Class 11 Government and Aided School Students",
        "name_tamil": "அரசு மற்றும் அரசு உதவிபெறும் பள்ளி 11-ஆம் வகுப்பு மாணவர்களுக்கான விலையில்லா மிதிவண்டி திட்டம்",
        "name_transliteration": "Vilayilla Midhivandi Thittam 11th Std",
        "department": "Education",
        "category": "welfare_grant",
        "description_english": "Provision of free bicycles to all boys and girls studying in class 11 in government and government-aided schools to facilitate easy commuting.",
        "description_tamil": "பள்ளிக்கு எளிதாக சென்று வர அரசு மற்றும் அரசு உதவிபெறும் பள்ளிகளில் 11-ஆம் வகுப்பு பயிலும் மாணவ-மாணவிகளுக்கு இலவச மிதிவண்டி வழங்கப்படுகிறது.",
        "benefit_amount": "இலவச மிதிவண்டி (Free Bicycle)",
        "source_url": "https://tnschools.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பள்ளி மாணவர் சேர்க்கை சான்று (School Bonafide)",
            "ஆதார் அட்டை (Aadhaar Card)",
            "குடும்ப அட்டை நகல்",
        ],
        "application_office": "பள்ளி தலைமை ஆசிரியர் அலுவலகம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "பள்ளி மூலமாக வழங்கப்படும்",
        "rules": [
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "higher_secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "15",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-CHIEF-MINISTER-BREAKFAST",
        "name_english": "Chief Minister's Breakfast Scheme for Primary School Children (Classes 1-5)",
        "name_tamil": "முதலமைச்சரின் காலை உணவுத் திட்டம் (தொடக்கப் பள்ளி 1 முதல் 5 வகுப்புகள்)",
        "name_transliteration": "Mudhalamaicharin Kaalai Unavu Thittam",
        "department": "Education",
        "category": "nutrition_support",
        "description_english": "Hot, hygienic, nutritious breakfast provided to all children studying in classes 1 to 5 in government primary schools across Tamil Nadu on all school working days.",
        "description_tamil": "அரசு தொடக்கப் பள்ளிகளில் 1 முதல் 5-ஆம் வகுப்பு வரை பயிலும் அனைத்து குழந்தைகளுக்கும் பள்ளிகளில் வழங்கப்படும் இலவச சத்தான காலை உணவு.",
        "benefit_amount": "இலவச காலை சத்தான உணவு",
        "source_url": "https://tnschools.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "அரசு தொடக்கப் பள்ளி மாணவர் சேர்க்கை பதிவு",
        ],
        "application_office": "பள்ளி தலைமை ஆசிரியர் அலுவலகம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "சேர்க்கையின் போதே உடனடியாக பொருந்தும்",
        "rules": [
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "primary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "5",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "11",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-SPECIAL-INCENTIVE-SC-GIRLS",
        "name_english": "Special Incentive Scheme for SC/ST Girl Students studying in 10th to 12th Standard",
        "name_tamil": "பட்டியலினம் மற்றும் பழங்குடியின 10 முதல் 12-ஆம் வகுப்பு பெண் குழந்தைகளுக்கான சிறப்பு ஊக்கத்தொகை",
        "name_transliteration": "SC ST Pengal Sirappu Ookkathogai 10-12",
        "department": "Education",
        "category": "scholarship",
        "description_english": "Special incentive to arrest dropout rates among Scheduled Caste and Scheduled Tribe girl students in secondary and higher secondary education.",
        "description_tamil": "பள்ளி இடைநிற்றலைத் தடுக்க 10, 11, மற்றும் 12-ஆம் வகுப்பு பயிலும் பட்டியலினம் மற்றும் பழங்குடியின மாணவிகளுக்கு வழங்கப்படும் சிறப்பு ஊக்கத்தொகை.",
        "benefit_amount": "₹1,500 to ₹2,000/year",
        "source_url": "https://adw.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (Community Certificate)",
            "பள்ளி சேர்க்கை சான்று (School Bonafide)",
            "மாணவி பெயரிலான வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "பள்ளி தலைமை ஆசிரியர் அலுவலகம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "gender",
                "operator": RuleOperator.EQUALS,
                "value": "female",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "SC,ST",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "secondary,higher_secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-PERIYAR-AWARD-GIRL-STUDENTS",
        "name_english": "Thanthai Periyar Memorial Award for BC/MBC Girl Students in Higher Secondary",
        "name_tamil": "தந்தை பெரியார் நினைவு பிற்படுத்தப்பட்டோர் மாணவியர் கல்வி ஊக்க விருது",
        "name_transliteration": "Thanthai Periyar Ninaivu Ninaivu Virudhu",
        "department": "Education",
        "category": "merit_award",
        "description_english": "Cash prize and certificate awarded to BC, MBC, and DNC girl students scoring top marks in 10th and 12th public examinations at district levels.",
        "description_tamil": "10 மற்றும் 12-ஆம் வகுப்பு பொதுத்தேர்வில் மாவட்ட அளவில் அதிக மதிப்பெண் பெறும் BC, MBC, DNC மாணவிகளுக்கு வழங்கப்படும் தந்தை பெரியார் நினைவு விருது.",
        "benefit_amount": "₹5,000 one-time",
        "source_url": "https://bcbmcmw.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (BC/MBC/DNC Community Certificate)",
            "10-ஆம் அல்லது 12-ஆம் வகுப்பு மதிப்பெண் சான்றிதழ் (Marksheet)",
            "பள்ளி மாற்றுச் சான்றிதழ் (TC) மற்றும் ஆதார் அட்டை",
        ],
        "application_office": "மாவட்ட பிற்படுத்தப்பட்டோர் நல அலுவலகம் / முதன்மைக் கல்வி அலுவலர் (CEO)",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "முடிவுகள் வெளியான பின் 45 நாட்கள்",
        "rules": [
            {
                "field_name": "gender",
                "operator": RuleOperator.EQUALS,
                "value": "female",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "BC,MBC,DNC",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "higher_secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-SPECIAL-SCHOLARSHIP-DISABILITY",
        "name_english": "Special Higher Education Scholarship for Differently Abled Students",
        "name_tamil": "மாற்றுத்திறனாளி மாணவர்களுக்கான சிறப்பு உயர்கல்வி உதவித்தொகை",
        "name_transliteration": "Maatru Thiranaali Kalvi Uvithogai",
        "department": "Education",
        "category": "scholarship",
        "description_english": "Scholarship grant and scribe allowance for visually challenged, hearing impaired, and locomotor disabled students pursuing higher secondary and undergraduate courses.",
        "description_tamil": "பார்வையற்றோர், காதுகேளாதோர் உள்ளிட்ட மாற்றுத்திறனாளி மாணவர்கள் மேல்நிலைக் கல்வி மற்றும் கல்லூரி படிப்பைத் தொடர வழங்கப்படும் சிறப்பு உதவித்தொகை.",
        "benefit_amount": "₹6,000 to ₹7,000/year",
        "source_url": "https://scd.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "மாற்றுத்திறனாளி தேசிய அடையாள அட்டை (UDID Card)",
            "கல்வி நிறுவன சேர்க்கை சான்றிதழ் (Bonafide Certificate)",
            "வங்கி கணக்கு புத்தகம்",
            "ஆதார் அட்டை",
        ],
        "application_office": "மாவட்ட மாற்றுத்திறனாளிகள் நல அலுவலகம் (DDWO)",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://scd.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "disability_status",
                "operator": RuleOperator.EQUALS,
                "value": "true",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "higher_secondary,graduate,postgraduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-BOARDING-GRANT-BC-MBC",
        "name_english": "Free Boarding Grant for BC/MBC/DNC Students in Hostels",
        "name_tamil": "பிற்படுத்தப்பட்டோர் மற்றும் மிகவும் பிற்படுத்தப்பட்டோர் தங்கும் விடுதி உணவுக் கட்டண மானியம்",
        "name_transliteration": "Vidhuthi Unavu Maaniyam BC MBC",
        "department": "Education",
        "category": "hostel_grant",
        "description_english": "Free boarding and lodging provided to rural poor BC, MBC, and DNC students admitted to department college and school hostels.",
        "description_tamil": "கிராமப்புற ஏழை BC, MBC, DNC மாணவர்கள் தங்கிப் படிக்க அரசு நலத்துறை விடுதிகளில் இலவச உணவு மற்றும் தங்குமிட வசதி.",
        "benefit_amount": "இலவச தங்குமிடம் மற்றும் உணவு (Free Boarding & Lodging)",
        "source_url": "https://bcbmcmw.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (Community Certificate)",
            "வருமானச் சான்றிதழ் (Income Certificate)",
            "பள்ளி/கல்லூரி சேர்க்கை சான்றிதழ்",
            "இருப்பிடச் சான்றிதழ் (வருவாய்த்துறை)",
        ],
        "application_office": "மாவட்ட பிற்படுத்தப்பட்டோர் மற்றும் சிறுபான்மையினர் நல அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://bcbmcmw.tn.gov.in/",
        "processing_time_estimate": "20 நாட்கள்",
        "rules": [
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "BC,MBC,DNC",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "8333",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-CLEANING-OCCUPATION-CHILDREN",
        "name_english": "Pre-Matric Scholarship to Children of Parents engaged in Unclean and Hazardous Occupations",
        "name_tamil": "தூய்மைப் பணியில் ஈடுபட்டுள்ள பெற்றோரின் குழந்தைகளுக்கு வழங்கப்படும் கல்வி உதவித்தொகை",
        "name_transliteration": "Thooymai Paniyaalar Kuzhanthaigal Kalvi Uvithogai",
        "department": "Education",
        "category": "scholarship",
        "description_english": "Special scholarship without caste or income ceiling for children whose parents are involved in hazardous cleaning and sanitation occupations.",
        "description_tamil": "சாதி மற்றும் வருமான வரம்பின்றி, தூய்மை மற்றும் சுகாதாரப் பணிகளில் ஈடுபட்டுள்ள பெற்றோரின் குழந்தைகளுக்கு வழங்கப்படும் பள்ளிக் கல்வி உதவித்தொகை.",
        "benefit_amount": "₹3,500 to ₹8,000/year",
        "source_url": "https://adw.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பெற்றோர் தூய்மைப் பணியாளர் என்பதற்கான உள்ளாட்சி அமைப்பு சான்றிதழ்",
            "பள்ளி பயிலும் சான்றிதழ் (School Study Certificate)",
            "மாணவர் பெயரிலான வங்கிக் கணக்கு புத்தகம்",
            "ஆதார் அட்டை",
        ],
        "application_office": "பள்ளி தலைமை ஆசிரியர் அலுவலகம் / மாவட்ட ஆதிதிராவிடர் நல அலுவலகம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "primary,secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "unclean_occupation_parent,sanitation_worker_family",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-CHIEF-MINISTER-MERIT-AWARD-SC",
        "name_english": "Chief Minister's Merit Award Scheme for SC and ST Students",
        "name_tamil": "முதலமைச்சரின் ஆதிதிராவிடர் மற்றும் பழங்குடியினர் சிறந்த மாணவர் தகுதி விருது",
        "name_transliteration": "Chief Minister Merit Award SC ST",
        "department": "Education",
        "category": "merit_award",
        "description_english": "Cash incentive of ₹3,000 per year awarded for up to 6 years for one boy and one girl from SC and ST communities in each district scoring highest in Plus Two exams.",
        "description_tamil": "12-ஆம் வகுப்பு பொதுத்தேர்வில் மாவட்ட அளவில் முதலிடம் பெறும் ஆதிதிராவிடர், பழங்குடியின மாணவ-மாணவியருக்கு ஆண்டுக்கு ₹3,000 வீதம் 6 ஆண்டுகளுக்கு வழங்கப்படும் விருது.",
        "benefit_amount": "₹3,000/year for 6 years",
        "source_url": "https://adwscholarship.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "12-ஆம் வகுப்பு அரசு பொதுத்தேர்வு மதிப்பெண் சான்றிதழ்",
            "சாதிச் சான்றிதழ் (SC/ST Community Certificate)",
            "தொடர்ந்து உயர்கல்வி பயில்வதற்கான கல்லூரி சேர்க்கை சான்று",
            "வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "மாவட்ட ஆதிதிராவிடர் மற்றும் பழங்குடியினர் நல அலுவலகம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "45 நாட்கள்",
        "rules": [
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "SC,ST",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "graduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-EDU-PM-YASASVI-OBC",
        "name_english": "PM YASASVI Pre-Matric Scholarship for OBC, EBC, and DNT Students (Classes 9 & 10)",
        "name_tamil": "பிஎம் யசஸ்வி இதர பிற்படுத்தப்பட்டோர் மற்றும் சீர்மரபினர் பள்ளி கல்வி உதவித்தொகை",
        "name_transliteration": "PM YASASVI Pre-Matric Scholarship",
        "department": "Education",
        "category": "scholarship",
        "description_english": "Centrally sponsored scholarship scheme implemented by Tamil Nadu government for meritorious OBC, EBC, and DNT students in classes 9 and 10 with annual family income up to ₹2.5 Lakhs.",
        "description_tamil": "ஆண்டு குடும்ப வருமானம் ₹2.5 லட்சத்திற்குள் உள்ள BC, MBC, DNC 9 மற்றும் 10-ஆம் வகுப்பு மாணவர்களுக்கான மத்திய-மாநில அரசின் பிஎம் யசஸ்வி கல்வி உதவித்தொகை.",
        "benefit_amount": "₹4,000/year",
        "source_url": "https://bcbmcmw.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "சாதிச் சான்றிதழ் (Community Certificate)",
            "வருமானச் சான்றிதழ் (Income Certificate - வருமானம் ₹2.5 லட்சத்திற்குள்)",
            "பள்ளி சேர்க்கை சான்று (School Bonafide)",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு",
        ],
        "application_office": "பள்ளி தலைமை ஆசிரியர் அலுவலகம் / தேசிய கல்வி உதவித்தொகை போர்ட்டல் (NSP)",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://bcbmcmw.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "caste_category",
                "operator": RuleOperator.IN_LIST,
                "value": "BC,MBC,DNC",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "20833",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
]
