import datetime
from app.models.enums import RuleOperator, RuleAppliesTo, ApplicationMode

LABOUR_SCHEMES = [
    {
        "scheme_code": "TN-LAB-UNEMPLOYMENT-ASSISTANCE-GRADUATE",
        "name_english": "Unemployment Assistance Scheme for Graduate and Post-Graduate Job Seekers",
        "name_tamil": "வேலைவாய்ப்பற்ற பட்டதாரி இளைஞர்களுக்கான மாதாந்திர உதவித்தொகை திட்டம்",
        "name_transliteration": "Velai Vaaippatra Pattadhari Maadhathira Uvithogai",
        "department": "Labour and Employment",
        "category": "unemployment_assistance",
        "description_english": "Monthly financial allowance provided for up to 3 years to unemployed graduates and post-graduates registered continuously for at least 5 years in employment exchanges.",
        "description_tamil": "வேலைவாய்ப்பு அலுவலகத்தில் 5 ஆண்டுகளுக்கு மேல் தொடர்ந்து பதிவு செய்து காத்திருக்கும் பட்டதாரி மற்றும் முதுகலை இளைஞர்களுக்கு வழங்கப்படும் மாதாந்திர உதவித்தொகை.",
        "benefit_amount": "₹600/month (₹1,800/quarter)",
        "source_url": "https://employmentexchange.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வேலைவாய்ப்பு அலுவலக பதிவு அடையாள அட்டை (Employment Card)",
            "பட்டப்படிப்பு / முதுகலை சான்றிதழ் (Degree Certificate)",
            "வருமானச் சான்றிதழ் (ஆண்டு வருமானம் ₹2,00,000-க்குள்)",
            "வேலையில்லை என்பதற்கான சுய அறிவிப்புப் படிவம்",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "மாவட்ட வேலைவாய்ப்பு மற்றும் தொழில்நெறி வழிகாட்டும் மையம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://employmentexchange.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "unemployed",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "graduate,postgraduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "20",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "40",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "16666",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-UNEMPLOYMENT-ASSISTANCE-HSC",
        "name_english": "Unemployment Assistance Scheme for Higher Secondary (12th Passed) Job Seekers",
        "name_tamil": "12-ஆம் வகுப்பு தேர்ச்சி பெற்ற வேலைவாய்ப்பற்ற இளைஞர்களுக்கான உதவித்தொகை",
        "name_transliteration": "12th Muditha Velai Vaaippatra Uvithogai",
        "department": "Labour and Employment",
        "category": "unemployment_assistance",
        "description_english": "Financial allowance of ₹400 per month given for up to 3 years to unemployed Plus Two candidates registered continuously with employment exchanges for 5 years.",
        "description_tamil": "மேல்நிலைக் கல்வி (12-ஆம் வகுப்பு) முடித்து 5 ஆண்டுகள் வேலைவாய்ப்பு அலுவலகத்தில் பதிவு செய்து காத்திருக்கும் இளைஞர்களுக்கு மாதம் ₹400 உதவி.",
        "benefit_amount": "₹400/month (₹1,200/quarter)",
        "source_url": "https://employmentexchange.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வேலைவாய்ப்பு அலுவலக பதிவு அட்டை (Employment Card)",
            "12-ஆம் வகுப்பு மதிப்பெண் சான்றிதழ்",
            "வருமானச் சான்றிதழ் (வட்டாட்சியர் அலுவலகம்)",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "மாவட்ட வேலைவாய்ப்பு மற்றும் தொழில்நெறி வழிகாட்டும் மையம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://employmentexchange.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "unemployed",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "higher_secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "40",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "16666",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-UNEMPLOYMENT-ASSISTANCE-SSLC",
        "name_english": "Unemployment Assistance Scheme for SSLC (10th Passed) Job Seekers",
        "name_tamil": "பத்தாம் வகுப்பு தேர்ச்சி பெற்ற வேலைவாய்ப்பற்றோருக்கான உதவித்தொகை",
        "name_transliteration": "10th Muditha Velai Vaaippatra Uvithogai",
        "department": "Labour and Employment",
        "category": "unemployment_assistance",
        "description_english": "Quarterly assistance of ₹900 (₹300/month) for up to 3 years to unemployed SSLC candidates registered for 5 continuous years in employment exchanges.",
        "description_tamil": "10-ஆம் வகுப்பு தேர்ச்சி பெற்று 5 ஆண்டுகள் வேலைவாய்ப்பு அலுவலகத்தில் பதிவு செய்து காத்திருக்கும் நபர்களுக்கு மாதம் ₹300 வீதம் காலாண்டுக்கு ₹900 உதவி.",
        "benefit_amount": "₹300/month (₹900/quarter)",
        "source_url": "https://employmentexchange.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வேலைவாய்ப்பு பதிவு அடையாள அட்டை",
            "10-ஆம் வகுப்பு மதிப்பெண் சான்றிதழ்",
            "வருமானச் சான்றிதழ்",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "மாவட்ட வேலைவாய்ப்பு அலுவலகம் / இ-சேவை மையம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://employmentexchange.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "unemployed",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.EQUALS,
                "value": "secondary",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "40",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "total_household_income",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "16666",
                "applies_to": RuleAppliesTo.FAMILY,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-UNEMPLOYMENT-ASSISTANCE-DISABLED",
        "name_english": "Special Unemployment Assistance for Differently Abled Job Seekers",
        "name_tamil": "மாற்றுத்திறனாளி வேலைவாய்ப்பற்றோருக்கான சிறப்பு உதவித்தொகை",
        "name_transliteration": "Maatru Thiranaali Velai Vaaippatra Sirappu Uvithogai",
        "department": "Labour and Employment",
        "category": "unemployment_assistance",
        "description_english": "Enhanced monthly unemployment allowance without upper age limit for differently abled job seekers registered continuously for at least 1 year in employment exchanges.",
        "description_tamil": "வேலைவாய்ப்பு அலுவலகத்தில் 1 ஆண்டு பதிவு செய்துள்ள மாற்றுத்திறனாளி வேலை தேடுவோருக்கு மாதம் ₹600 முதல் ₹1,000 வரை வழங்கப்படும் சிறப்பு உதவித்தொகை.",
        "benefit_amount": "₹600 to ₹1,000/month",
        "source_url": "https://employmentexchange.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "மாற்றுத்திறனாளி தேசிய அடையாள அட்டை (UDID Card)",
            "வேலைவாய்ப்பு பதிவு அட்டை (Employment Registration Card)",
            "கல்விச் சான்றிதழ்கள்",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "மாவட்ட வேலைவாய்ப்பு அலுவலகம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://employmentexchange.tn.gov.in/",
        "processing_time_estimate": "20 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "unemployed",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "disability_status",
                "operator": RuleOperator.EQUALS,
                "value": "true",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-CONSTRUCTION-BOARD-PENSION",
        "name_english": "Tamil Nadu Construction Workers Welfare Board Monthly Pension Scheme (Age 60+)",
        "name_tamil": "தமிழ்நாடு கட்டுமானத் தொழிலாளர்கள் நல வாரிய முதியோர் ஓய்வூதியம்",
        "name_transliteration": "Kattumana Thozhilaalar Nala Vaariya Oivoodhiyam",
        "department": "Labour and Employment",
        "category": "pension",
        "description_english": "Monthly pension of ₹1,000 provided to registered building and construction workers who have reached 60 years of age and completed at least 5 years of registration in the board.",
        "description_tamil": "கட்டுமானத் தொழிலாளர்கள் நல வாரியத்தில் 5 ஆண்டுகளுக்கு மேல் பதிவு செய்து 60 வயது பூர்த்தியடைந்த தொழிலாளர்களுக்கு மாதம் ₹1,000 ஓய்வூதியம்.",
        "benefit_amount": "₹1,000/month",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "கட்டுமான நல வாரிய உறுப்பினர் அடையாள அட்டை (TNUWWB Smart Card)",
            "வயதுச் சான்றிதழ் (ஆதார் / வாக்காளர் அட்டை - 60 வயது பூர்த்தி)",
            "வாரிய சந்தா செலுத்திய ரசீது / புதுப்பித்தல் விவரம்",
            "வங்கி கணக்கு புத்தகம் (Bank Passbook)",
        ],
        "application_office": "தொழிலாளர் உதவி ஆணையர் (சமூகப் பாதுகாப்புத் திட்டம்) அலுவலகம் / TNUWWB போர்ட்டல்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "60",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "registered_construction_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-CONSTRUCTION-BOARD-ACCIDENT-RELIEF",
        "name_english": "Tamil Nadu Construction Workers Welfare Board Accidental Death and Disability Relief",
        "name_tamil": "கட்டுமானத் தொழிலாளர்கள் விபத்து மரணம் மற்றும் ஊன நிவாரண நிதி",
        "name_transliteration": "Kattumana Thozhilaalar Vibathu Nivarana Nidhi",
        "department": "Labour and Employment",
        "category": "accident_relief",
        "description_english": "Ex-gratia financial assistance of ₹5,00,000 in case of accidental death at worksite or ₹1,00,000 to ₹5,00,000 for permanent total disability for registered construction workers.",
        "description_tamil": "பணியிட விபத்தில் உயிரிழக்கும் பதிவு பெற்ற கட்டுமானத் தொழிலாளர்களின் குடும்பத்திற்கு ₹5,00,000 மற்றும் நிரந்தர ஊனத்திற்கு ₹1,00,000 முதல் ₹5,00,000 வரை நிவாரணம்.",
        "benefit_amount": "₹5,00,000 for accidental death",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வாரிய உறுப்பினர் அட்டை (TNUWWB Registration Card)",
            "முதல் தகவல் அறிக்கை (FIR) மற்றும் பிரேத பரிசோதனை அறிக்கை (Postmortem Report)",
            "இறப்புச் சான்றிதழ் மற்றும் வாரிசுச் சான்றிதழ்",
            "வாரிசுதாரர் ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "தொழிலாளர் உதவி ஆணையர் (சமூகப் பாதுகாப்புத் திட்டம்) அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "registered_construction_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "60",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-CONSTRUCTION-BOARD-MARRIAGE-ASSISTANCE",
        "name_english": "Tamil Nadu Construction Workers Welfare Board Marriage Financial Assistance",
        "name_tamil": "கட்டுமானத் தொழிலாளர்கள் நல வாரிய திருமண நிதி உதவி",
        "name_transliteration": "Kattumana Thozhilaalar Thirumana Nidhi Uvithogai",
        "department": "Labour and Employment",
        "category": "marriage_assistance",
        "description_english": "Marriage financial assistance of ₹5,000 for male workers and ₹7,000 for female workers (or their children) provided by the Construction Workers Welfare Board.",
        "description_tamil": "பதிவு பெற்ற கட்டுமானத் தொழிலாளி அல்லது அவர்களின் மகன்/மகள் திருமணத்திற்கு ₹5,000 (ஆண்) மற்றும் ₹7,000 (பெண்) திருமண நிதி உதவி.",
        "benefit_amount": "₹5,00,0 (Men) / ₹7,000 (Women)",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "கட்டுமான நல வாரிய உறுப்பினர் அட்டை",
            "திருமண அழைப்பிதழ் மற்றும் திருமணப் பதிவுச் சான்றிதழ் (Marriage Certificate)",
            "மணமகன் மற்றும் மணமகள் வயதுச் சான்றிதழ்",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "TNUWWB இணையதளம் / மாவட்ட தொழிலாளர் அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "registered_construction_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "marital_status",
                "operator": RuleOperator.EQUALS,
                "value": "married",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-CONSTRUCTION-BOARD-MATERNITY",
        "name_english": "Maternity Financial Assistance for Registered Female Construction Workers",
        "name_tamil": "பதிவுபெற்ற பெண் கட்டுமானத் தொழிலாளர்களுக்கான மகப்பேறு உதவித்தொகை",
        "name_transliteration": "Pen Kattumana Thozhilaalar Magapperu Uvithogai",
        "department": "Labour and Employment",
        "category": "maternity_benefit",
        "description_english": "Maternity assistance of ₹6,000 (₹3,000 on delivery and ₹3,000 after 30 days) and miscarriage assistance of ₹3,000 for registered female construction workers.",
        "description_tamil": "வாரியத்தில் பதிவுபெற்ற பெண் கட்டுமானத் தொழிலாளர்களுக்கு குழந்தை பிறப்பின் போது ₹6,000 மகப்பேறு உதவித்தொகை வழங்கும் திட்டம்.",
        "benefit_amount": "₹6,000 (₹3,000 on delivery, ₹3,000 post-delivery)",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வாரிய உறுப்பினர் அடையாள அட்டை (TNUWWB ID)",
            "அரசு மருத்துவமனை குழந்தை பிறப்புச் சான்றிதழ் (Birth Certificate)",
            "தாய் சேய் நல அட்டை (RCH ID card)",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "தொழிலாளர் நல வாரிய போர்ட்டல் / தொழிலாளர் உதவி ஆணையர்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "20 நாட்கள்",
        "rules": [
            {
                "field_name": "gender",
                "operator": RuleOperator.EQUALS,
                "value": "female",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "registered_construction_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "19",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "40",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-CONSTRUCTION-BOARD-EDUCATION",
        "name_english": "Educational Assistance Scheme for Children of Registered Construction Workers",
        "name_tamil": "கட்டுமானத் தொழிலாளர்களின் குழந்தைகளுக்கு வழங்கப்படும் கல்வி உதவித்தொகை",
        "name_transliteration": "Kattumana Thozhilaalar Kuzhanthaigal Kalvi Uvithogai",
        "department": "Labour and Employment",
        "category": "education_assistance",
        "description_english": "Annual educational scholarship ranging from ₹1,000 to ₹12,000 per year for children of registered construction workers studying from 10th to Post Graduate and professional degrees.",
        "description_tamil": "10-ஆம் வகுப்பு முதல் தொழிற்கல்வி, பட்டப்படிப்பு வரை பயிலும் கட்டுமானத் தொழிலாளர்களின் குழந்தைகளுக்கு ஆண்டுதோறும் ₹1,000 முதல் ₹12,000 வரை கல்வி உதவி.",
        "benefit_amount": "₹1,000 to ₹12,000/year",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "பெற்றோரின் கட்டுமான நல வாரிய உறுப்பினர் அட்டை",
            "மாணவர் பயிலும் சான்றிதழ் (Bonafide Certificate)",
            "கடந்த ஆண்டு மதிப்பெண் சான்றிதழ்",
            "மாணவர் பெயரிலான வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "TNUWWB போர்ட்டல் / தொழிலாளர் உதவி ஆணையர் அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.EQUALS,
                "value": "student",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "education_level",
                "operator": RuleOperator.IN_LIST,
                "value": "secondary,higher_secondary,graduate,postgraduate",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "construction_worker_child",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-UNORGANIZED-WORKERS-PENSION",
        "name_english": "Tamil Nadu Unorganized Workers Welfare Board Monthly Pension Scheme",
        "name_tamil": "தமிழ்நாடு அமைப்புசாரா உடலுழைப்புத் தொழிலாளர்கள் நல வாரிய ஓய்வூதியம்",
        "name_transliteration": "Amaippusaara Thozhilaalar Oivoodhiyam",
        "department": "Labour and Employment",
        "category": "pension",
        "description_english": "Monthly social security pension of ₹1,000 provided to manual and unorganized workers aged 60 and above registered under the Tamil Nadu Manual Workers Welfare Board.",
        "description_tamil": "அமைப்புசாரா உடலுழைப்புத் தொழிலாளர்கள் நல வாரியத்தில் பதிவு செய்து 60 வயது பூர்த்தியடைந்த தொழிலாளர்களுக்கு மாதம் ₹1,000 முதியோர் ஓய்வூதியம்.",
        "benefit_amount": "₹1,000/month",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "அமைப்புசாரா தொழிலாளர் நல வாரிய உறுப்பினர் அட்டை (TNUWWB Card)",
            "வயதுச் சான்றிதழ் (60 வயது பூர்த்தி)",
            "ஆதார் அட்டை (Aadhaar Card)",
            "வங்கி கணக்கு புத்தகம் (Bank Passbook)",
        ],
        "application_office": "மாவட்ட தொழிலாளர் சமூகப் பாதுகாப்புத் திட்ட அலுவலகம் / TNUWWB போர்ட்டல்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "60",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "unorganized_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-MANUAL-WORKERS-ACCIDENT-RELIEF",
        "name_english": "Manual Workers Social Security Scheme - Natural Death and Funeral Relief",
        "name_tamil": "அமைப்புசாரா உடலுழைப்புத் தொழிலாளர்கள் இயற்கை மரணம் & ஈமச்சடங்கு நிதி",
        "name_transliteration": "Udaluzhaippu Thozhilaalar Eemachadangu Nidhi",
        "department": "Labour and Employment",
        "category": "death_relief",
        "description_english": "Financial grant of ₹20,000 for natural death and ₹5,000 for funeral expenses provided to nominees of registered manual workers in unorganized sectors.",
        "description_tamil": "அமைப்புசாரா தொழிலாளர்கள் இயற்கை மரணமடைந்தால் குடும்பத்தினருக்கு ₹20,000 மற்றும் உடனடியாக ₹5,000 ஈமச்சடங்கு உதவித்தொகை வழங்கும் திட்டம்.",
        "benefit_amount": "₹25,000 (Natural Death Relief + Funeral Assistance)",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "இறந்த தொழிலாளியின் நல வாரிய அட்டை",
            "இறப்புச் சான்றிதழ் (Death Certificate)",
            "வாரிசுச் சான்றிதழ் (Legal Heir Certificate)",
            "வாரிசுதாரர் ஆதார் மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "மாவட்ட தொழிலாளர் அலுவலகம் / TNUWWB",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "15 நாட்கள்",
        "rules": [
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "unorganized_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-DRIVER-BOARD-VEHICLE-ASSISTANCE",
        "name_english": "Tamil Nadu Auto Rickshaws and Taxi Drivers Welfare Board Welfare Scheme",
        "name_tamil": "தமிழ்நாடு ஆட்டோ மற்றும் வாடகை வாகன ஓட்டுநர்கள் நல வாரிய உதவி",
        "name_transliteration": "Auto Vaadagai Vaagana Ottunargal Nala Vaariya Uvithogai",
        "department": "Labour and Employment",
        "category": "welfare_grant",
        "description_english": "Comprehensive welfare benefits including accidental relief (₹5,00,000), pension, marriage aid, and spectacles assistance for auto and taxi drivers.",
        "description_tamil": "ஆட்டோ மற்றும் வாடகை வாகன ஓட்டுநர்கள் நல வாரியத்தில் பதிவு பெற்ற ஓட்டுநர்களுக்கு விபத்து நிவாரணம், திருமணம், கல்வி மற்றும் கண் கண்ணாடி உதவித்தொகை.",
        "benefit_amount": "Accident Relief (₹5,00,000) & Welfare Grants",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வாகன ஓட்டுநர் நல வாரிய அட்டை",
            "செல்லத்தக்க ஓட்டுநர் உரிமம் (Commercial Driving License with Badge)",
            "ஆதார் அட்டை மற்றும் குடும்ப அட்டை",
            "வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "மாவட்ட தொழிலாளர் உதவி ஆணையர் அலுவலகம்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "occupation",
                "operator": RuleOperator.IN_LIST,
                "value": "self_employed,private_employee,daily_wage",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "auto_taxi_driver,driver_license",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-TAILORING-BOARD-ASSISTANCE",
        "name_english": "Tamil Nadu Tailoring Workers Welfare Board Maternity and Spectacles Assistance",
        "name_tamil": "தமிழ்நாடு தையல் தொழிலாளர்கள் நல வாரிய மகப்பேறு & மூக்குக்கண்ணாடி உதவி",
        "name_transliteration": "Thaiyal Thozhilaalar Nala Vaariya Uvithogai",
        "department": "Labour and Employment",
        "category": "welfare_grant",
        "description_english": "Spectacles purchase reimbursement of ₹500, maternity assistance of ₹6,000, and pension benefits for registered tailoring and garment workers.",
        "description_tamil": "தையல் தொழிலாளர் நல வாரிய உறுப்பினர்களுக்கு கண் பார்வைக் குறைபாட்டிற்கு கண்ணாடி வாங்க ₹500 மற்றும் மகப்பேறு உதவித்தொகை ₹6,000 வழங்கும் திட்டம்.",
        "benefit_amount": "₹500 for Spectacles, ₹6,000 Maternity Assistance",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "தையல் தொழிலாளர் நல வாரிய உறுப்பினர் அட்டை",
            "கண் மருத்துவப் பரிசோதனைச் சீட்டு / ரசீது",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "மாவட்ட தொழிலாளர் அலுவலகம் / TNUWWB",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "20 நாட்கள்",
        "rules": [
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "tailoring_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-DOMESTIC-WORKERS-WELFARE",
        "name_english": "Tamil Nadu Domestic Workers Welfare Board Social Security Assistance",
        "name_tamil": "தமிழ்நாடு வீட்டுப் பணியாளர்கள் நல வாரிய சமூகப் பாதுகாப்பு உதவி",
        "name_transliteration": "Veettu Paniyaalargal Nala Vaariya Uvithogai",
        "department": "Labour and Employment",
        "category": "welfare_grant",
        "description_english": "Accident insurance, maternity benefit, pension (₹1,000/month), and education assistance for registered female domestic maids, cooks, and cleaners.",
        "description_tamil": "வீட்டு வேலை செய்யும் பெண் தொழிலாளர்களுக்கு மாதம் ₹1,000 முதியோர் ஓய்வூதியம், விபத்து நிவாரணம் மற்றும் குழந்தைகள் கல்வி உதவித்தொகை.",
        "benefit_amount": "₹1,000/month Pension (Age 60+), Marriage & Education Aid",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "வீட்டுப் பணியாளர் நல வாரிய அடையாள அட்டை",
            "பணிபுரியும் குடியிருப்பு உரிமையாளர் அல்லது குடியிருப்போர் நல சங்க சான்று",
            "ஆதார் அட்டை மற்றும் வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "மாவட்ட தொழிலாளர் உதவி ஆணையர் அலுவலகம்",
        "application_mode": ApplicationMode.BOTH,
        "online_application_url": "https://tnuwwb.tn.gov.in/",
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "gender",
                "operator": RuleOperator.EQUALS,
                "value": "female",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "domestic_worker",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-SKILL-TRAINING-TNSDC",
        "name_english": "Tamil Nadu Skill Development Corporation (TNSDC) Free Youth Skill Training with Stipend",
        "name_tamil": "தமிழ்நாடு திறன் மேம்பாட்டுக் கழகம் (நான் முதல்வன்) இளைஞர் இலவச திறன் பயிற்சி",
        "name_transliteration": "Naan Mudhalvan Thiran Membattu Payirchi",
        "department": "Labour and Employment",
        "category": "skill_training",
        "description_english": "Free market-aligned technical and vocational skill training courses with industry certification, placement assistance, and ₹1,000/month stipend for unemployed youth.",
        "description_tamil": "வேலையில்லாத இளைஞர்களுக்கு தொழில் துறை சார்ந்த இலவச தொழில்நுட்ப திறன் பயிற்சி, மாதம் ₹1,000 உதவித்தொகை மற்றும் வேலைவாய்ப்பு ஏற்பாடு.",
        "benefit_amount": "Free Certification Training + ₹1,000/month Stipend",
        "source_url": "https://naanmudhalvan.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "கல்வித் தகுதிச் சான்றிதழ் (10th/12th/Diploma/Degree Marksheet)",
            "ஆதார் அட்டை (Aadhaar Card)",
            "பாஸ்போர்ட் அளவு புகைப்படம்",
            "வங்கி கணக்கு புத்தகம்",
        ],
        "application_office": "மாவட்ட திறன் பயிற்சி அலுவலகம் / நான் முதல்வன் போர்ட்டல்",
        "application_mode": ApplicationMode.ONLINE,
        "online_application_url": "https://naanmudhalvan.tn.gov.in/",
        "processing_time_estimate": "பயிற்சி தொகுதி தொடங்கும் போது",
        "rules": [
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "18",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "age",
                "operator": RuleOperator.LESS_OR_EQUAL,
                "value": "35",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "occupation",
                "operator": RuleOperator.IN_LIST,
                "value": "unemployed,student",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
    {
        "scheme_code": "TN-LAB-HANDLOOM-WEAVERS-PENSION",
        "name_english": "Tamil Nadu Handloom Weavers Social Security and Pension Scheme",
        "name_tamil": "தமிழ்நாடு கைத்தறி நெசவாளர் முதியோர் ஓய்வூதியத் திட்டம்",
        "name_transliteration": "Kaithari Nesavaalar Oivoodhiya Thittam",
        "department": "Labour and Employment",
        "category": "pension",
        "description_english": "Monthly old age pension of ₹1,000 provided to aged handloom and powerloom weavers who have reached 60 years of age and are unable to earn livelihood.",
        "description_tamil": "60 வயது பூர்த்தியடைந்த, நலிவடைந்த கைத்தறி மற்றும் விசைத்தறி நெசவாளர்களுக்கு மாதம் ₹1,000 முதியோர் ஓய்வூதியம் வழங்கும் திட்டம்.",
        "benefit_amount": "₹1,000/month",
        "source_url": "https://tnuwwb.tn.gov.in/",
        "last_verified_date": datetime.date(2026, 8, 1),
        "is_active": True,
        "required_documents": [
            "கைத்தறி கூட்டுறவு சங்க உறுப்பினர் அட்டை",
            "நெசவாளர் அடையாள அட்டை",
            "வயதுச் சான்றிதழ் (60 வயது பூர்த்தி)",
            "ஆதார் அட்டை மற்றும் வங்கி பாஸ்புக்",
        ],
        "application_office": "கைத்தறி மற்றும் துணிநூல் துறை உதவி இயக்குநர் அலுவலகம் / கூட்டுறவு சங்கம்",
        "application_mode": ApplicationMode.OFFLINE,
        "online_application_url": None,
        "processing_time_estimate": "30 நாட்கள்",
        "rules": [
            {
                "field_name": "age",
                "operator": RuleOperator.GREATER_OR_EQUAL,
                "value": "60",
                "applies_to": RuleAppliesTo.PERSON,
            },
            {
                "field_name": "special_flags",
                "operator": RuleOperator.IN_LIST,
                "value": "handloom_weaver",
                "applies_to": RuleAppliesTo.PERSON,
            },
        ],
    },
]
